name: ECS Project Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: "Set to true to destroy all resources"
        required: false
        default: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init -upgrade

      - name: Terraform Validate
        if: github.event.inputs.destroy != 'true'
        working-directory: ./Terraform
        run: terraform validate

      - name: Terraform Format
        if: github.event.inputs.destroy != 'true'
        working-directory: ./Terraform
        run: terraform fmt -recursive

      - name: Terraform Plan
        if: github.event.inputs.destroy != 'true'
        working-directory: ./Terraform
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event.inputs.destroy != 'true'
        working-directory: ./Terraform
        run: terraform apply -auto-approve -input=false

      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        working-directory: ./Terraform
        run: terraform destroy -auto-approve -input=false
